
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: admin

development:
  <<: *default
  database: myclan_development

test:
  <<: *default
  database: myclan_test

production:
  <<: *default
  database: myclan_production

